# src/main/resources/application.yml
spring:
  application:
    name: medical-center-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:medical_center}
    username: ${DB_USER:medical_user}
    password: ${DB_PASSWORD:securepassword123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  security:
    jwt:
      secret: ${JWT_SECRET:defaultSecretKey}
      expiration: 86400000 # 24 horas