# .github/workflows/backend-ci.yml
name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn -f backend/pom.xml clean package
      
    - name: Run Tests
      run: mvn -f backend/pom.xml test
      
    - name: Docker Build
      run: docker build -t centromedico/backend:latest ./backend
      
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag centromedico/backend:latest centromedico/backend:${{ github.sha }}
        docker push centromedico/backend:latest
        docker push centromedico/backend:${{ github.sha }}